### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by marek22k** [amnezia-vpn/amneziawg-tools#19]
Hello,

it would be nice if a .deb Debian package could be published for easy installation.

Related: https://github.com/amnezia-vpn/amneziawg-go/issues/44

**Comment by leninalive** [comment]
Hi,

Debian packages are available for kernel module and tools in Launchpad's PPA - https://launchpad.net/~amnezia/+archive/ubuntu/ppa

For Go version we have no plans to build DEB/RPM packages as it is out of Go ideology.
