### ISSUE TITLE
wg-tools does not seem to understand new parameters

### ISSUE THREAD

**Issue by valerius2k** [amnezia-vpn/amneziawg-tools#5]
Hi. Tried to build this repo and use it with "wg" and "wg-quick" and "wg-quick@" systemd unit.

# wg-quick up wg10

[#] ip link add wg10 type wireguard
[#] wg setconf wg10 /dev/fd/63
Unable to modify interface: Invalid argument
[#] ip link delete dev wg10

I have the following wg10.conf:

`[Interface]
PrivateKey = *censored*
Address = 10.78.77.2/32,fd42:43:42::2/128
DNS = 1.1.1.1,9.9.9.9
PostUp = ip rule add from 10.77.77.248/29 table 128; ip route add table 128 defa
PostDown = ip rule del from 10.77.77.248/29 table 128; ip route del table 128 de
Table = off
S1 = 9
S2 = 11
Jc = 12
Jmin = 120
Jmax = 220

[Peer]
PublicKey = *censored*
PresharedKey = *censored*
Endpoint = 192.162.241.137:443
AllowedIPs = 0.0.0.0/0,::/0
`

"wg" does not seem to understand the new parameters S1, S2, Jc, Jmin, Jmax. Though, I see them present in config.c source file. What I'm doing wrong? Maybe, I need to build other branch than "master"?

**Comment by valerius2k** [comment]
Ah, It seems, I'm missing the awg-linux-kernel-module file.

**Comment by leninalive** [comment]
@valerius2k we hope you have achieved success with newer versions of packages so we close this issue.
